language: objective-c
script:
- xctool -project "ObjectiveCPP.xcodeproj" -scheme "ObjectiveCPP Mac Static Library (C++11)" build test
before_install:
- bash Scripts/travis-before.sh
after_success:
- bash Scripts/travis-after.sh
